development:
  adapter: async

test:
  adapter: test

production:
  # TODO: redisにしよう
  adapter: async
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: tickly_production
